// automatically generated by the FlatBuffers compiler, do not modify

package battlecode.schema;

@SuppressWarnings("unused")
public final class WinType {
  private WinType() { }
  public static final byte RESIGNATION = 0;
  public static final byte MORE_POINTS = 1;
  public static final byte MORE_ROBOTS = 2;
  public static final byte MORE_CHEESE = 3;
  public static final byte TIE = 4;
  public static final byte COIN_FLIP = 5;

  public static final String[] names = { "RESIGNATION", "MORE_POINTS", "MORE_ROBOTS", "MORE_CHEESE", "TIE", "COIN_FLIP", };

  public static String name(int e) { return names[e]; }
}

